### ISSUE TITLE
Webpage not showing anything other than wind wheel 

### ISSUE THREAD

**Issue by sbbagal13** [mayansalama/windmill#26]
Hi team, 

I have started windmill project with default configuration but webpage not showing anything , other that wind wheel (I followed ReadMe to install and run with default airflow )

Here is the logs from terminal

* Serving Flask app 'windmill.http.api.endpoints' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
[2021-08-25 22:08:45,836] {_internal.py:225} WARNING -  * Running on all addresses.
   WARNING: This is a development server. Do not use it in a production deployment.
[2021-08-25 22:08:45,836] {_internal.py:225} INFO -  * Running on http://10.32.7.185:8000/ (Press CTRL+C to quit)
[2021-08-25 22:09:10,858] {_internal.py:225} INFO - 10.32.3.1 - - [25/Aug/2021 22:09:10] "GET / HTTP/1.1" 200 -
[2021-08-25 22:09:10,887] {_internal.py:225} INFO - 10.32.3.1 - - [25/Aug/2021 22:09:10] "GET /App.40f70a3e.js HTTP/1.1" 200 -
[2021-08-25 22:09:11,254] {_internal.py:225} INFO - 10.32.3.1 - - [25/Aug/2021 22:09:11] "GET /favicon.ea4855f9.ico HTTP/1.1" 200 -

Can someone help here?

**Comment by mayansalama** [comment]
Gday mate - cards on the table I haven't looked at this in a long while and it's by no means ready for prod. Last time I tested this was with Airflow 1.10.4, so that might be a good place to start. Based on the logs it looks like the frontend isn't routing to the backend correctly - try running the dev server, you might be getting blocked by CORS.

**Comment by sbbagal13** [comment]
Thanks @mayansalama  for your reply.
Do we know any similar open source project which provide Drag and drop for Building Airflow DAGS ?

**Comment by mayansalama** [comment]
Nothing I'm aware of - @TomKlimovski have you heard of anything?

**Comment by TomKlimovski** [comment]
Not open source, no. @sbbagal13 out of curiosity, what use-case are you trying to solve for?

**Comment by sbbagal13** [comment]
@TomKlimovski , I have requirement to create Drag and Drop like environment to Create Airflow DAGs, So non-python business executives also can create and run it. I was exploring Rabix Composer but it don't have opensource web version and not having inbuilt operators. While searching came across this project , so trying to run and explore it. If it works I can contribute to work it for new version and some more functionalities

**Comment by TomKlimovski** [comment]
Cool, I understand now; @mayansalama can correct me if I'm wrong but this was created to get you 'most of the way there', and wasn't initially intended for a production-hardened drag-and-drop tooling solution. 
More of a use-case would be to get 80% of the DAG done with non-python people, then the developers take it the rest of the way to prod with proper Gitflow processes. 
Last I checked this all worked locally, if I get some time this week I can verify

**Comment by sbbagal13** [comment]
Thanks @TomKlimovski  and @mayansalama  , I have deployed it on Docker but I think internal code having hardcoded 127.0.0.1 host for communication so I am not able to see anything on webpage.

**Comment by sbbagal13** [comment]
@TomKlimovski  , I did some changes to local hardcoded address to run it on Docker but now facing below Errors, Not sure how to resolve it , If you get some time to make it working let me know , we can put updated version together 

Traceback (most recent call last):
  File "/opt/venv/lib/python3.6/site-packages/windmill/models/operators/operator_index.py", line 34, in marshall_operator_list
    handlers.append(OperatorHandler.from_operator(operator))
  File "/opt/venv/lib/python3.6/site-packages/windmill/models/operators/operator_handler.py", line 57, in from_operator
    ) from e
windmill.exceptions.OperatorMarshallError: Unable to parse class TimeSensor
[2021-08-26 02:45:02,129] {class_parser.py:62} WARNING - Unable to parse field airflow.models.DAG
[2021-08-26 02:45:02,130] {operator_index.py:36} ERROR - Unable to parse operator SqlSensor: Unable to parse class SqlSensor
Traceback (most recent call last):
  File "/opt/venv/lib/python3.6/site-packages/windmill/models/operators/operator_handler.py", line 52, in from_operator
    *cls.docstring_parser.parse_class(operator, inherit_until=BaseOperator)
  File "/opt/venv/lib/python3.6/site-packages/windmill/utils/class_parser.py", line 114, in parse_class
    name, props = ClassParser._parse_class_docstring(cls, inherited)
  File "/opt/venv/lib/python3.6/site-packages/windmill/utils/class_parser.py", line 71, in _parse_class_docstring
    raise DocstringParseError(f"Class {cls} has no docstring")
windmill.exceptions.DocstringParseError:

**Comment by sbbagal13** [comment]
Issue has been resolved with updating code to latest package structure of the Airflow
